### ISSUE TITLE
Conflicts with other zstd libraries on Ubuntu 22.04

### ISSUE THREAD

**Issue by 20kdc** [TechnologicalPizza/SharpZstd#1]
On Ubuntu 22.04, the zstd library shipped with this package conflicts with the system library, so when the system library is loaded in the same process, the process may fail to load this library or may crash.

I've determined a workaround for most cases but I'm not sure how to apply it here - the fix is to apply `-Xlinker -Bsymbolic` in both CFLAGS and LDFLAGS.

However vcpkg is involved and I'm not sure what that does to things in this case.

It is worth noting that the symbol conflict involved here cannot occur in reverse, as dlopen will not expose symbols by default. (see: https://github.com/swaroop-sridhar/coreclr/blob/master/src/pal/src/loader/module.cpp#L954 )

**Comment by TechPizzaDev** [comment]
Thanks for showing interest in this little repo. I've been in talks with a few people on Discord about this since it's very common for Linux machines. 
I've applied `-Xlinker -Bsymbolic` for the Linux build and GitHub Actions have produced a new package. Could you test it and see if it actually fixes it? Will do a release later if everything goes smoothly.

**Comment by 20kdc** [comment]
I don't appear to have access to the artifact, sorry.

**Comment by 20kdc** [comment]
Ok, so I can download the artifact, I just completely failed to navigate GitHub's actions UI to find the right place, and the API stuff wasn't helpful since it for some reason wanted some stuff about OAuth scopes.
But now I should be able to test the library, so will do.

**Comment by 20kdc** [comment]
I wasn't able to actually use the package directly (I am not aware of a way to actually use a specific NuGet package file), but having extracted and tested the native library, it works properly now.

**Comment by 20kdc** [comment]
So having been made aware of a way to use a specific NuGet package file, I tested it and it now works just fine.

Not closing yet because I'm not sure if your closing policy is based on state-of-master or state-of-release, but everything checks out here. Thank you!

**Comment by TechPizzaDev** [comment]
Fixed with [f51f5c3](https://github.com/TechnologicalPizza/SharpZstd/commit/f51f5c3d036f01c8b103c9b538762dee19e6f887).
Thanks for testing!
